#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user
while IFS= read -r line;
do
	echo "$line" | cut -d ":" -f 1,3,6
done < "/etc/passwd"
