#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
while [ $counter -lt 21 ];
do	
	case $counter in
		5) echo $"bad luck from China";;
		10) echo $"bad luck from Japan";;
		18) echo "bad luck from Italy"
	esac
	echo $counter
	((counter=counter+1))
done
