#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
h=1
m=1
while [ $h -lt 13 ];
do
	echo "Hour: "$h
	while [ $m -lt 60 ];
	do
		echo $m
		((m=m+1))
	done
	m=1
	((h=h+1))
done
