#!/usr/bin/env bash
# This script is displaying
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash
# is displayed (refer to the example)

for x in $(ls);
	do echo $x | cut -d '-' -f 2;
done
